init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
artifacts:
  - path: artifacts\build\*.nupkg
build_script:
  - build.cmd --quiet verify
clone_depth: 1
test: off
deploy: off